### PR TITLE
azurerm: fix #352 admin_password

### LINKED ISSUE #352: Azure: Set a valide admin_password with azurerm_windows_virtual_machine
**General information:**

* Operating System: 
* Terracognita version / tag: master
* Did you build Terracognita from sources or did you use the Docker image: sources

**Describe the bug:**

When importing `azurerm_windows_virtual_machine`, `admin_password` can't be read.
By default, the value is set to `ignored-as-imported` which is not a valid password for Azure.

A solution would be to set a "valid" password such `Ignored-as-!mport3d`.

**Log message**

`Error: "admin_password" has to fulfill 3 out of these 4 conditions: Has lower characters, Has upper characters, Has a digit, Has a special character other than "_", fullfiled only 2 conditions`

**Additional context**

### PR DESCRIPTION
**Pull request by talset**
The value can't be retrieved. Terraform Azure provider set "ignored-as-imported" which is not a valid password. In this case, set the default password wich respects Azure constraints

### CODE REVIEW

File: azurerm/provider.go [hunk 1]
```diff
@@ -177,6 +177,13 @@ func (a *azurerm) FixResource(t string, v cty.Value) (cty.Value, error) {
 			if len(path) == 3 {
 				if gas, ok := path[0].(cty.GetAttrStep); ok {
 					switch gas.Name {
+					case "os_profile":
+						switch path[2].(cty.GetAttrStep).Name {
+						case "admin_password":
+							// The value can't be retrieved. Terraform Azure provider set "ignored-as-imported" which is not a valid password.
+							// In this case, set the default password wich respects Azure constraints
```
Comment (xescugc) [inline azurerm/provider.go:184]: s/wich/which/

File: azurerm/provider.go [hunk 2]
```diff
@@ -249,6 +256,10 @@ func (a *azurerm) FixResource(t string, v cty.Value) (cty.Value, error) {
 			if len(path) > 0 {
 				if gas, ok := path[0].(cty.GetAttrStep); ok {
 					switch gas.Name {
+					case "admin_password":
+						// The value can't be retrieved. Terraform Azure provider set "ignored-as-imported" which is not a valid password.
+						// In this case, set the default password wich respects Azure constraints
```
Comment (xescugc) [inline azurerm/provider.go:261]: s/wich/which/

**Review by xescugc — CHANGES_REQUESTED** [review]

**Review by xescugc — APPROVED** [review]
