### PR TITLE
provider: Added 'Version' to the Provider interface

### LINKED ISSUE #374: `aws_lambda_function`:  "filename": one of `filename,image_uri,s3_bucket` must be specified
**General information:**

* Operating System:  
* Terracognita version / tag: 
* Did you build Terracognita from sources or did you use the Docker image: 

**Describe the bug:**

When importing an `aws_lambda_function` we get the following error

```
"filename": one of `filename,image_uri,s3_bucket` must be specified
```

**Log message**

Here you can paste the log message or paste the link to console logs. If the log message is too big, you can use a tool like https://pastebin.com/.

**Additional context**

### LINKED ISSUE #378: `aws_s3_bucket`: Value for unconfigurable attribute `arn` and `hosted_zone_id`
**General information:**

* Operating System: 
* Terracognita version / tag:
* Did you build Terracognita from sources or did you use the Docker image: 

**Describe the bug:**

When importing `aws_s3_bucket` we get this errors:

```
Can't configure a value for "hosted_zone_id": its value will be decided automatically based on the result of applying this configuration.
```
or 
```
Can't configure a value for "arn": its value will be decided automatically based on the result of applying this configuration.
```

**Log message**

Here you can paste the log message or paste the link to console logs. If the log message is too big, you can use a tool like https://pastebin.com/.

**Additional context**

### LINKED ISSUE #392: When upgrading the providers set the new version to the code
### Abstract

After https://github.com/cycloidio/terracognita/pull/391 all the providers have a `cost version = "VERSION"` which has the value of the version we are currently importing, this value should automatically be set when we run `make update-terraform-provider` so we do not have to manually maintain it.

The version on HCL has to not have the prefix `v` so we'll have to strip it up

### PR DESCRIPTION
**Pull request by xescugc**
Now each provider will have to specify to which version they are importing, this way we can later on set this version to the provider configuration on the HCL. This way we prevent compatibility issues between provider versions

Closes #378, closes #374, closes #392

### CODE REVIEW

File: aws/provider.go [hunk 1]
```diff
@@ -20,6 +20,9 @@ import (
 	"github.com/pkg/errors"
 )
 
+// version of the Terraform provider, this is automatically changed with the 'make update-terraform-provider'
+const version = "4.9.0"
```
Comment (talset) [inline aws/provider.go:24]:
```suggestion
const version = "5.1.0"
```

lets use the latest one ;)

**Review by talset — APPROVED** [review]

**Comment by xescugc** [comment]
All providers have greater versions but I did not update any so I can do it individually as I had issues when I tried on a previous PR.

**Review by talset — APPROVED** [review]
