### PR TITLE
hcl: Integration between Interpolation and Modules changed

### LINKED ISSUE #219: AWS Provider error about variables.
**General information:**

* Operating System: ArchLinux
* Terracognita version / tag: git build
* Did you build Terracognita from sources or did you use the Docker image: Built from source

**Describe the bug:**

Error saying variables maynot be used here when running terraform init.

**Log message**

╷
│ Error: Variables not allowed
│ 
│ On module-main/variables.tf line 2630: Variables may not be used here.
╵

**Additional context**

image

### PR DESCRIPTION
**Pull request by xescugc**
Now if only Modules is activated, interpolation is deactivated and if it has ModuleVariables only those
specific attributes will not be interpolated so we do not end up with invalid HCL

Closes #219

### CODE REVIEW

File: hcl/writer.go [hunk 1]
```diff
@@ -465,9 +465,21 @@ func writeTuple(pbody, body *hclwrite.Body, attr string, value cty.Value) {
 }
 
 // Interpolate replaces the hardcoded resources link
-// with TF interpolation
+// with TF interpolation.
+// I has the following format:
```
Comment (xlr-8) [inline hcl/writer.go:469]: I have*

File: hcl/writer.go [hunk 2]
```diff
@@ -465,9 +465,21 @@ func writeTuple(pbody, body *hclwrite.Body, attr string, value cty.Value) {
...
+// * VALUE => ${aws_instance.name.attribute}
+// So then each value matching the VALUE will
+// be replaced with the reference
 func (w *Writer) Interpolate(i map[string]string) {
-	if !w.opts.Interpolate {
+	// If Interpolation is disabled or
```
Comment (xlr-8) [inline hcl/writer.go:474]: I'm sorry to ask silly questions, but how/who decides if "interpolation" is disabled? Wouldn't it be the code detecting it's not needed?

File: hcl/writer.go [hunk 3]
```diff
@@ -465,9 +465,21 @@ func writeTuple(pbody, body *hclwrite.Body, attr string, value cty.Value) {
...
+	// a module without specific attributes to
+	// create as variables (so all are variables),
```
Comment (xlr-8) [inline hcl/writer.go:476]: Meaning no call to a module? And simple `variable` block?

File: hcl/writer.go [hunk 4]
```diff
@@ -465,9 +465,21 @@ func writeTuple(pbody, body *hclwrite.Body, attr string, value cty.Value) {
...
+	// we ignore the Interpolation as this may happend and is invalid
+	// variable "aws_ses_identity_notification_topic_XoqJb_identity" {
+	//   default = aws_ses_domain_mail_from.SSWXE.id
+	// }
```
Comment (xlr-8) [inline hcl/writer.go:480]: This is invalid because terraform forbids it? I thought it got addressed https://github.com/hashicorp/terraform/issues/18069 - no?

File: hcl/writer.go (hunk 1 above)
Comment (xescugc) [reply hcl/writer.go:469]: It has*

haah

File: hcl/writer.go (hunk 2 above)
Comment (xescugc) [reply hcl/writer.go:474]: We have an `--interpolate` flag, by default is `true`.

File: hcl/writer.go (hunk 3 above)
Comment (xescugc) [reply hcl/writer.go:476]: If you have a `--module my-module` without the `--module-variables` it would replace all values for variables, so no interpolation needed as everything would be a variable.

File: hcl/writer.go (hunk 4 above)
Comment (xescugc) [reply hcl/writer.go:480]: This is a reference, not a variable.

**Review by xlr-8 — APPROVED** [review]
RS

File: hcl/writer.go (hunk 2 above)
Comment (xlr-8) [reply hcl/writer.go:474]: Shouldn't one of the test be with `Interpolate false` ?

**Comment by xescugc** [comment]
Done

**Review by xlr-8 — APPROVED** [review]
