### PR TITLE
aws: fix #171 RequestError when service not available

### LINKED ISSUE #171: eu-south-1 fail scan
**General information:**

* Operating System: 
Docker image running on MacOs
* Terracognita version / tag:
cycloid/terracognita                 latest                                                  a3d38f3fc231   8 months ago    407MB

* Did you build Terracognita from sources or did you use the Docker image: 
Docker
**Describe the bug:**
while running 
```
docker run cycloid/terracognita aws --region eu-south-1 `cat .aws/credentials | paste - - - |grep def | awk '{print "--access-key "$4" --secret-key "$7}'` --hcl test.tf -d
```
got this error:

**Log message**
```
ts=2021-03-27T21:38:18.839282862Z caller=import.go:82 func=provider.Import resource=aws_ses_active_receipt_rule_set msg="fetching the list of resources"
Error: could not import from AWS: RequestError: send request failed
caused by: Post "https://email.eu-south-1.amazonaws.com/": dial tcp 15.161.191.156:443: i/o timeout
error while reading from resource "aws_ses_active_receipt_rule_set"
github.com/cycloidio/terracognita/aws.(*aws).Resources
	/app/aws/provider.go:74
github.com/cycloidio/terracognita/provider.Import
	/app/provider/import.go:91
github.com/cycloidio/terracognita/cmd.glob..func2
	/app/cmd/aws.go:86
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/app/main.go:11
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
github.com/cycloidio/terracognita/provider.Import
	/app/provider/import.go:93
github.com/cycloidio/terracognita/cmd.glob..func2
	/app/cmd/aws.go:86
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/app/main.go:11
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
could not import from AWS: RequestError: send request failed
caused by: Post "https://email.eu-south-1.amazonaws.com/": dial tcp 15.161.191.156:443: i/o timeout
error while reading from resource "aws_ses_active_receipt_rule_set"
github.com/cycloidio/terracognita/aws.(*aws).Resources
	/app/aws/provider.go:74
github.com/cycloidio/terracognita/provider.Import
	/app/provider/import.go:91
github.com/cycloidio/terracognita/cmd.glob..func2
	/app/cmd/aws.go:86
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/app/main.go:11
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
github.com/cycloidio/terracognita/provider.Import
	/app/provider/import.go:93
github.com/cycloidio/terracognita/cmd.glob..func2
	/app/cmd/aws.go:86
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/app/main.go:11
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
Usage:
  terracognita aws [flags]
  terracognita aws [command]

Available Commands:
  resources   List of all the AWS supported Resources

Flags:
      --access-key string   Access Key (required)
  -h, --help                help for aws
      --region string       Region to search in, for now * it's not supported (required)
      --secret-key string   Secret Key (required)
  -t, --tags strings        List of tags to filter with format 'NAME:VALUE'

Global Flags:
  -d, --debug             Activate the debug mode wich includes TF logs via TF_LOG=TRACE|DEBUG|INFO|WARN|ERROR configuration https://www.terraform.io/docs/internals/debugging.html
  -e, --exclude strings   List of resources to not import, this names are the ones on TF (ex: aws_instance). If not set then means that none the resources will be excluded
      --hcl string        HCL output file
  -i, --include strings   List of resources to import, this names are the ones on TF (ex: aws_instance). If not set then means that all the resources will be imported
      --target strings    List of resources to import via ID, those IDs are the ones documented on Terraform that are needed to Import. The format is 'aws_instance.ID'
      --tfstate string    TFState output file
  -v, --verbose           Activate the verbose mode

Use "terracognita aws [command] --help" for more information about a command.
```
Here you can paste the log message or paste the link to console logs. If the log message is too big, you can use a tool like https://pastebin.com/.

**Additional context**

### PR DESCRIPTION
**Pull request by talset**
Skip RequestError raised when there is an issue on network layer.
Mainly happen when a AWS service is not available on the requested region.

+ Update readme regarding new provider.tf format

Fix #171

### CODE REVIEW

File: provider/resource.go [hunk 1]
```diff
@@ -275,7 +275,7 @@ func (r *resource) Read(f *filter.Filter) error {
 	// so we have to do it manually
 	// it's not all of them though
 	for _, t := range f.Tags {
-		if v, ok := r.data.GetOk(fmt.Sprintf("%s.%s", r.Provider().TagKey(), t.Name)); ok && v.(string) != t.Value {
+		if v, ok := r.data.GetOk(fmt.Sprintf("%s.%s", r.Provider().TagKey(), t.Name)); !ok || v.(string) != t.Value {
```
Comment (xescugc) [inline provider/resource.go:278]: Are you sure about this?

The `ok` is validating that the value exists, and then it validates that has the right value, by changing it if does not exists it will not be of type `string` and potentially fail the conversion. Also if it does not exists it makes no sense to compare it to `t.Value`.

So IDK if this is fixing anything or potentially adding a bug.

Comment (talset) [reply provider/resource.go:278]: You are right, one condition is missing. I should be something like `!ok || (ok && v.(string) != t.Value)`

Comment (talset) [reply provider/resource.go:278]: You are right, one condition is missing. I should be something like !ok || (ok && v.(string) != t.Value)

Comment (talset) [reply provider/resource.go:278]: Correct me if I'm wrong `!ok` ensure to skip/return if the key 'tags' doesn't exist. if it doesn't exist, the first condition will be `!ok -> true` and the second condition will not be tested.
And only when the key "tags" exist, we will test the second condition ?



`!ok` || v.(string) != t.Value

Comment (xescugc) [reply provider/resource.go:278]: Ok yes I read it too quick haha.

**Review by xescugc — APPROVED** [review]
