### PR TITLE
aws: Changed from Message to Code check on errors

### LINKED ISSUE #171: eu-south-1 fail scan
**General information:**

* Operating System: 
Docker image running on MacOs
* Terracognita version / tag:
cycloid/terracognita                 latest                                                  a3d38f3fc231   8 months ago    407MB

* Did you build Terracognita from sources or did you use the Docker image: 
Docker
**Describe the bug:**
while running 
```
docker run cycloid/terracognita aws --region eu-south-1 `cat .aws/credentials | paste - - - |grep def | awk '{print "--access-key "$4" --secret-key "$7}'` --hcl test.tf -d
```
got this error:

**Log message**
```
ts=2021-03-27T21:38:18.839282862Z caller=import.go:82 func=provider.Import resource=aws_ses_active_receipt_rule_set msg="fetching the list of resources"
Error: could not import from AWS: RequestError: send request failed
caused by: Post "https://email.eu-south-1.amazonaws.com/": dial tcp 15.161.191.156:443: i/o timeout
error while reading from resource "aws_ses_active_receipt_rule_set"
github.com/cycloidio/terracognita/aws.(*aws).Resources
	/app/aws/provider.go:74
github.com/cycloidio/terracognita/provider.Import
	/app/provider/import.go:91
github.com/cycloidio/terracognita/cmd.glob..func2
	/app/cmd/aws.go:86
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/app/main.go:11
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
github.com/cycloidio/terracognita/provider.Import
	/app/provider/import.go:93
github.com/cycloidio/terracognita/cmd.glob..func2
	/app/cmd/aws.go:86
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/app/main.go:11
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
could not import from AWS: RequestError: send request failed
caused by: Post "https://email.eu-south-1.amazonaws.com/": dial tcp 15.161.191.156:443: i/o timeout
error while reading from resource "aws_ses_active_receipt_rule_set"
github.com/cycloidio/terracognita/aws.(*aws).Resources
	/app/aws/provider.go:74
github.com/cycloidio/terracognita/provider.Import
	/app/provider/import.go:91
github.com/cycloidio/terracognita/cmd.glob..func2
	/app/cmd/aws.go:86
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/app/main.go:11
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
github.com/cycloidio/terracognita/provider.Import
	/app/provider/import.go:93
github.com/cycloidio/terracognita/cmd.glob..func2
	/app/cmd/aws.go:86
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/app/main.go:11
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
Usage:
  terracognita aws [flags]
  terracognita aws [command]

Available Commands:
  resources   List of all the AWS supported Resources

Flags:
      --access-key string   Access Key (required)
  -h, --help                help for aws
      --region string       Region to search in, for now * it's not supported (required)
      --secret-key string   Secret Key (required)
  -t, --tags strings        List of tags to filter with format 'NAME:VALUE'

Global Flags:
  -d, --debug             Activate the debug mode wich includes TF logs via TF_LOG=TRACE|DEBUG|INFO|WARN|ERROR configuration https://www.terraform.io/docs/internals/debugging.html
  -e, --exclude strings   List of resources to not import, this names are the ones on TF (ex: aws_instance). If not set then means that none the resources will be excluded
      --hcl string        HCL output file
  -i, --include strings   List of resources to import, this names are the ones on TF (ex: aws_instance). If not set then means that all the resources will be imported
      --target strings    List of resources to import via ID, those IDs are the ones documented on Terraform that are needed to Import. The format is 'aws_instance.ID'
      --tfstate string    TFState output file
  -v, --verbose           Activate the verbose mode

Use "terracognita aws [command] --help" for more information about a command.
```
Here you can paste the log message or paste the link to console logs. If the log message is too big, you can use a tool like https://pastebin.com/.

**Additional context**

### LINKED ISSUE #176: Failing to run in eu-west-1
**General information:**

* Operating System: MacOS Big Sur
* Terracognita version / tag: v0.6.2
* Did you build Terracognita from sources or did you use the Docker image: installed from Brew

**Describe the bug:**

When running against our AWS account with resources in `eu-west-1`,  we get a 403 when terracognita tries to call endpoints in API Gateway. Not only are there no resources in API Gateway in this account, but this is being run with AWSAdministratorAccess, so no permissions issues should occur. 

I think this could be related to #171, where assumptions about certain resources existing in all regions is not true. 

**Log message**

```
ts=2021-04-01T10:54:41.332899Z caller=provider.go:39 func=reader.New msg="configuring aws Reader"
ts=2021-04-01T10:54:42.021977Z caller=provider.go:52 func=aws.NewProvider msg="configuring TF Client"
ts=2021-04-01T10:54:42.995209Z caller=aws.go:99 func=cmd.aws.RunE msg="initializing HCL writer"
ts=2021-04-01T10:54:42.995278Z caller=aws.go:108 func=cmd.aws.RunE msg=importing
ts=2021-04-01T10:54:42.99529Z caller=aws.go:111 func=cmd.aws.RunE msg="starting terracognita" version=v0.6.2
ts=2021-04-01T10:54:42.995316Z caller=import.go:66 func=provider.Import filters="\n\tTags:    [],\n\tInclude: [],\n\tExclude: [],\n\tTargets: [],\n"
ts=2021-04-01T10:54:42.996259Z caller=import.go:82 func=provider.Import resource=aws_instance msg="fetching the list of resources"
ts=2021-04-01T10:54:43.073336Z caller=import.go:168 func=provider.Import resource=aws_instance msg="importing done"
ts=2021-04-01T10:54:43.073514Z caller=import.go:82 func=provider.Import resource=aws_alb msg="fetching the list of resources"
ts=2021-04-01T10:54:43.22091Z caller=import.go:168 func=provider.Import resource=aws_alb msg="importing done"
ts=2021-04-01T10:54:43.221132Z caller=import.go:82 func=provider.Import resource=aws_alb_listener msg="fetching the list of resources"
ts=2021-04-01T10:54:43.221206Z caller=import.go:168 func=provider.Import resource=aws_alb_listener msg="importing done"
ts=2021-04-01T10:54:43.221245Z caller=import.go:82 func=provider.Import resource=aws_alb_listener_certificate msg="fetching the list of resources"
ts=2021-04-01T10:54:43.221288Z caller=import.go:168 func=provider.Import resource=aws_alb_listener_certificate msg="importing done"
ts=2021-04-01T10:54:43.221323Z caller=import.go:82 func=provider.Import resource=aws_alb_listener_rule msg="fetching the list of resources"
ts=2021-04-01T10:54:43.221357Z caller=import.go:168 func=provider.Import resource=aws_alb_listener_rule msg="importing done"
ts=2021-04-01T10:54:43.22139Z caller=import.go:82 func=provider.Import resource=aws_alb_target_group msg="fetching the list of resources"
ts=2021-04-01T10:54:43.258598Z caller=import.go:168 func=provider.Import resource=aws_alb_target_group msg="importing done"
ts=2021-04-01T10:54:43.258847Z caller=import.go:82 func=provider.Import resource=aws_alb_target_group_attachment msg="fetching the list of resources"
ts=2021-04-01T10:54:43.296053Z caller=import.go:168 func=provider.Import resource=aws_alb_target_group_attachment msg="importing done"
ts=2021-04-01T10:54:43.296187Z caller=import.go:82 func=provider.Import resource=aws_api_gateway_deployment msg="fetching the list of resources"
Error: could not import from AWS: AccessDeniedException:
        status code: 403, request id: 55c361c4-2b0e-4cd9-996f-26ed909f7a49
error while reading from resource "aws_api_gateway_deployment"
github.com/cycloidio/terracognita/aws.(*aws).Resources
        github.com/cycloidio/terracognita/aws/provider.go:93
github.com/cycloidio/terracognita/provider.Import
        github.com/cycloidio/terracognita/provider/import.go:91
github.com/cycloidio/terracognita/cmd.glob..func2
        github.com/cycloidio/terracognita/cmd/aws.go:112
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        github.com/cycloidio/terracognita/main.go:11
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
github.com/cycloidio/terracognita/provider.Import
        github.com/cycloidio/terracognita/provider/import.go:98
github.com/cycloidio/terracognita/cmd.glob..func2
        github.com/cycloidio/terracognita/cmd/aws.go:112
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        github.com/cycloidio/terracognita/main.go:11
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
```

### PR DESCRIPTION
**Pull request by xescugc**
And added a new one to the list 'AccessDeniedException'

To make the change on the Error handling I checked which was the error we had to fix on https://github.com/cycloidio/terracognita/issues/138 and checked the code from AWS to format errors so I knew which Code to expect.

Closes #176

### CODE REVIEW

File: aws/provider.go [hunk 1]
```diff
@@ -16,13 +16,14 @@ import (
 	tfaws "github.com/terraform-providers/terraform-provider-aws/aws"
 )
 
-// skippableErrors is a list of errors
+// skippableCodes is a list of errors
```
Comment (kerak19) [inline aws/provider.go:19]: Hmm, should it be `a list of codes` since you changed name from `...Errors` to `...Codes` ?

**Review by kerak19 — APPROVED** [review]
Seems good

**Comment by xescugc** [comment]
Fixed and RS directly

**Review by kerak19 — APPROVED** [review]
